package Boundry;

import Controller.ProsesManager;
import Entity.Dokumen;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        file_path = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Open File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Proses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bulan", "Hasil Panen", "Pemupukan", "Hasil prediksi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton4.setText("Next");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(file_path, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(file_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setSelectedFile(new File(""));
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false); //mematikan akses Allfile pada laman input file
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel", "xlsx");
        chooser.addChoosableFileFilter(filter);
        if (chooser.showOpenDialog(this) == JFileChooser.OPEN_DIALOG) {
            File selectedFile = chooser.getSelectedFile();
            file_path.setText(selectedFile.getAbsolutePath());
            JOptionPane.showMessageDialog(null, "berhasil load data");

        }
    }//GEN-LAST:event_jButton1ActionPerformed
//mean error
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ProsesManager pm = new ProsesManager();
        Dokumen dkm = new Dokumen();
        ArrayList<ArrayList> data = dkm.load_excel(file_path.getText());
        if (data.get(0).size() > 3) {
            JOptionPane.showMessageDialog(rootPane, "data tidak sesuai");
        } else {
            //dari file yang telah di upload langsung di kirim ke class proses prediksi pada proses manager
            pm.do_proses_prediksi(data);
            //dikembalikan nilai data dari proses manager ke fungsi button proses untuk ditampilkan pada table
            ArrayList<Double> prediksi = pm.prediksi;
            ArrayList<Double> selisih = pm.selisih;
            ArrayList<Double> mean = pm.mean;
            ArrayList<ArrayList> angka = pm.data_angka;
            DefaultTableModel data_header = new DefaultTableModel(new String[]{
                "Bulan",
                "Hasil panen",
                "pemupukan",
                "Bulan",
                "Hasil panen",
                "Prediksi"
            }, 0);
            jTable1.setModel(data_header); // set table header

            double pembagian = 12;
            double sum_mean_all = 0;
            for (int i = 0; i < prediksi.size(); i++) {
//            System.out.println(prediksi.size());
//            System.out.println(angka.get(2));
                sum_mean_all += mean.get(i);
                data_header.addRow(new Object[]{
                    //menampilkan data pada table
                    i + 1,
                    Double.parseDouble(angka.get(i).get(0).toString()),
                    Double.parseDouble(angka.get(i).get(1).toString()),
                    i + 2,
                    Double.parseDouble(angka.get(i).get(2).toString()),
                    prediksi.get(i)
                });
            }
        }
//        ProsesManager pm = new ProsesManager();
//        Dokumen dkm = new Dokumen();
//        ArrayList<ArrayList>  data=dkm.load_excel(file_path.getText());
//        
//        //dari file yang telah di upload langsung di kirim ke class proses prediksi pada proses manager
//        pm.do_proses_prediksi(data);
//        //dikembalikan nilai data dari proses manager ke fungsi button proses untuk ditampilkan pada table
//         ArrayList<Double>  prediksi=pm.prediksi;
//          ArrayList<Double>  selisih=pm.selisih;
//           ArrayList<Double>  mean=pm.mean;
//         ArrayList<ArrayList>  angka=pm.data_angka;
//        DefaultTableModel data_header = new DefaultTableModel(new String[]{
//            "Bulan",
//            "Hasil panen real",
//            "pemupukan",
//            "Prediksi"
//        }, 0);
//        jTable1.setModel(data_header); // set table header
//        
//        double pembagian = 12;
//        double sum_mean_all=0;
//        for (int i = 0; i < prediksi.size(); i++) {
////            System.out.println(prediksi.size());
////            System.out.println(angka.get(2));
//            sum_mean_all+=mean.get(i);
//            data_header.addRow(new Object[]{
//                //menampilkan data pada table
//                i + 1,
//                Double.parseDouble(angka.get(i).get(2).toString()),
//                Double.parseDouble(angka.get(i).get(1).toString()),
//                prediksi.get(i)
//            });
//        }
//        //nilai total mean error akan dibagi dengan total bulan
//        mean_error_text.setText(String.valueOf(sum_mean_all));
//        jLabel2.setText(String.valueOf(pembagian));
//        double persen_error = sum_mean_all /12;
//        jLabel3.setText(String.valueOf(persen_error));
//        //nilai persen keberhasilan didapat dari 100% - total akhir mean error %
//        double persen_total = 100 - persen_error;
//        jLabel4.setText(String.valueOf(persen_total));
    }//GEN-LAST:event_jButton2ActionPerformed

//pindah frame
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        new NewJFrame1(file_path.getText()).setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField file_path;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
